<a href="https://colab.research.google.com/github/ParkHyunsu1110/Machine-Learning/blob/main/2021_09_17_DataProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Handling of Missing Data

In [ ]:
import numpy as np # used for handling numbers
import pandas as pd #used for handling  the dataset

In [ ]:
from sklearn.impute import SimpleImputer # used for handling missing data
from sklearn.preprocessing import LabelEncoder # used for encoding categorical data
from sklearn.model_selection import train_test_split # used for splitting training and testing data
from sklearn.preprocessing import StandardScaler # used for feature scaling

In [ ]:
dataset = pd.read_csv('DataPreprocessing.csv') # to import the dataset into a variable
#splititing the attributes innto independent and dependent attributes
X = dataset.iloc[:, :-1].values #attributes to determine dependent variable / Class
Y = dataset.iloc[:, -1].values # dependent variable / Class

In [ ]:
X

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, nan],
       ['India', 40.0, 69600.0],
       ['Brazil', nan, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [ ]:
X[:, 1:]

array([[49.0, 86400.0],
       [32.0, 57600.0],
       [35.0, 64800.0],
       [43.0, 73200.0],
       [45.0, 76533.33333333333],
       [40.0, 69600.0],
       [43.77777777777778, 62400.0],
       [53.0, 94800.0],
       [55.0, 99600.0],
       [42.0, 80400.0]], dtype=object)

Handling of Categorical Data

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [ ]:
X

array([[1, 49.0, 86400.0],
       [0, 32.0, 57600.0],
       [2, 35.0, 64800.0],
       [0, 43.0, 73200.0],
       [2, 45.0, nan],
       [1, 40.0, 69600.0],
       [0, nan, 62400.0],
       [1, 53.0, 94800.0],
       [2, 55.0, 99600.0],
       [1, 42.0, 80400.0]], dtype=object)

Feature Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()
X = minmax_scaler.fit_transform(X)
print(X)

[[0.5        0.73913043 0.68571429]
 [0.         0.         0.        ]
 [1.         0.13043478 0.17142857]
 [0.         0.47826087 0.37142857]
 [1.         0.56521739        nan]
 [0.5        0.34782609 0.28571429]
 [0.                nan 0.11428571]
 [0.5        0.91304348 0.88571429]
 [1.         1.         1.        ]
 [0.5        0.43478261 0.54285714]]
